categoria:
        resource: "@BackendBundle/Resources/config/routing/categoria.yml"
        prefix:   /categoria

movimentacao:
        resource: "@BackendBundle/Resources/config/routing/movimentacao.yml"
        prefix:   /movimentacao

produto:
        resource: "@BackendBundle/Resources/config/routing/produto.yml"
        prefix:   /produto
    

