       
categoria:
        resource: "@BackendBundle/Resources/config/routing/categoria.yml"
        prefix:   /categoria

produto:
        resource: "@BackendBundle/Resources/config/routing/produto.yml"
        prefix:   /produto
    

