categoria_list:
    path:     /
    defaults: { _controller: "BackendBundle:Categoria:index" }

categoria_new:
    path:     /novo
    defaults: { _controller: "BackendBundle:Categoria:new" }

categoria_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Categoria:create" }
    requirements: { _method: post }

categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Categoria:edit" }

categoria_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Categoria:update" }
    requirements: { _method: post|put }

categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Categoria:delete" }
    requirements: { _method: post|delete }
