<?php

namespace Intrix\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository {

    public function getAllAtivos() {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('c')
                ->from('BackendBundle:Categoria', 'c')
                ->where("c.status = '1'");


        return $query;
    }

}
