<?php

namespace Intrix\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendaRepository extends EntityRepository
{
}
